/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC_02_Wed_12_Group;
import java.util.Scanner;


public class App {
    public static void main(String[] args) {
        admin adminUser = new admin();
        boolean isAdmin = false;
        NewUser user = new NewUser();
        Scanner sc = new Scanner(System.in);

        // Check login type
        System.out.println("1.Admin \n2.User \n3.Exit");
        String userOutput = sc.nextLine();

        // Admin login
        if (userOutput.equals("1")) {
            System.out.println("Please type your username:");
            userOutput = sc.nextLine();
            if (!userOutput.equals("admin123")) {
                System.out.println("Please enter correct username!");
                return;
            } else {
                System.out.println("Please type your password:");
                userOutput = sc.nextLine();
                if (!userOutput.equals("admin123")) {
                    System.out.println("Please enter correct password!");
                    return;
                }
            }
            // Admin has provided correct login info
            isAdmin = true;
        }

        else if (userOutput.equals("3")) {
            System.out.println("Bye!");
            return;
        }


        while (true) {
            // Admin
            if (isAdmin) {
                adminUser.refresh();
                System.out.println("1.View \n2.Summary \n3.Table \n4.Edit \n5.Add \n6.Exit");
                userOutput = sc.nextLine();
                if (userOutput.equals("4") || userOutput.equals("5")) {
                    adminUser.adminFuncitonality(Integer.parseInt(userOutput));
                }
                else if (userOutput.equals("6")) {
                    System.out.println("Bye!");
                    return;
                } else if (userOutput.equals("1") || userOutput.equals("2") || userOutput.equals("3")){
                    user.userFunctionality(Integer.parseInt(userOutput));
                }
            }

            // User
            else {
                user.refresh();
                System.out.println("1.View \n2.Summary \n3.Table \n4.Exit");
                userOutput = sc.nextLine();
                if (userOutput.equals("4")) {
                    System.out.println("Bye!");
                    return;
                }
                user.userFunctionality(Integer.parseInt(userOutput));
            }

        }

    }
}