/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC_02_Wed_12_Group;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
}
